config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             :controllers => {:registrations => 'custom_devise/registrations', :sessions => 'custom_devise/sessions'}

  get "/users", to: "users#index", as: 'redirect_users_to_reg'

  get "/api/sessions", to: "users#sessions", as: "sessions"
  post "/api/sessions/export", to: "users#export_key", as: "sessions_export_key"
  get "/api/sessions/logout", to: "users#logout", as: "logout"
  get "/api/sessions/balance", to: "users#balance", as: 'session_balance'

  # Profile
  get "/api/profiles/active", to: "profiles#profile_active", as: "profile_active"
  get "/api/profiles/search", to: "profiles#profile_search", as: "profile_info_search"
  get "/api/profiles/:address", to: "profiles#profile_info_deprecated", as: "profile_info_deprecated"
  get "/api/profiles/:address/basic", to: "profiles#profile_basic_info", as: "profile_basic_info"
  get "/api/profiles/:address/extended", to: "profiles#profile_info", as: "profile_info"
  get "/api/profiles/:address/likes", to: "profiles#likes", as: "profile_likes"
  get "/api/profiles/:address/followers", to: "profiles#followers", as: "profile_followers"
  get "/api/profiles/:address/following", to: "profiles#following", as: "profile_following"

  # Profile updates
  post "/api/profiles/name", to: "profiles#update_profile_name", as: "update_profile_name"
  post "/api/profiles/avatar", to: "profiles#update_profile_avatar", as: "update_profile_avatar"
  post "/api/profiles/bio", to: "profiles#update_profile_bio", as: "update_profile_bio"
  post "/api/profiles/header", to: "profiles#update_profile_header", as: "update_profile_header"
  post "/api/profiles/following/:address", to: "profiles#profile_follow_user", as: "profile_follow_user"
  delete "/api/profiles/following/:address", to: "profiles#profile_unfollow_user", as: "profile_unfollow_user"

  # Communities
  get "/api/communities/index", to: "posts#get_communities", as: "get_communities"
  get "/api/posts/communities/query", to: "posts#get_community_posts", as: "get_community_posts_query"
  get "/api/posts/communities/:community_name/index", to: "posts#get_community_posts", as: "get_community_posts"

  # Posts
  get "/api/posts/replies/index", to: "posts#get_reply_feed", as: "get_reply_feed"
  get "/api/posts/top/index", to: "posts#top", as: "top_posts"
  get "/api/posts/feed/index", to: "posts#feed", as: "feed_posts"
  get "/api/posts/search/hashtag/:hashtag", to: "posts#search", as: "search_posts"
  get "/api/posts/profiles/:address_id/index", to: "posts#profile_posts", as: "profile_posts"

  get "/api/posts/tx/:tx_id", to: "posts#single_post", as: "single_post"
  post "/api/posts", to: "posts#create_post", as: "create_post"
  post "/api/posts/tx/:tx_id", to: "posts#repost_post", as: "repost_post"

  # Notifications
  get "/api/notifications/index", to: "posts#get_notifications", as: "get_notifications"

  # Post replies
  get "/api/posts/tx/:tx_id/replies", to: "posts#get_replies", as: "get_replies"
  post "/api/posts/tx/:tx_id/replies", to: "posts#create_reply", as: "create_reply"

  # Post likes
  get "/api/posts/tx/:tx_id/likes", to: "posts#likes", as: "post_likes"
  post "/api/posts/tx/:tx_id/likes", to: "posts#create_like", as: "create_like"

  # Post photos
  get "/api/posts/tx/:tx_id/photos", to: "posts#photos", as: "post_photos"
  post "/api/posts/tx/:tx_id/photos", to: "posts#attach_photo", as: "attach_photo"

  root to: 'home#index'
end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :user, :through => :account_manager
  has_many :account_manager
  has_many :stream
  has_many :network_connection
  has_many :network_credential
  has_many :stream_source

  def managed_by?(user)
    AccountManager.where(:account_id => self.id, :user_id => user.id).first != nil
  end

  def has_valid_twitter_connection?
    false
  end
end

app/models/account_manager.rb
class AccountManager < ActiveRecord::Base
  belongs_to :user
  belongs_to :account
end

app/models/address_hashtag.rb
class AddressHashtag < ActiveRecord::Base
end

app/models/address_ident.rb
class AddressIdent < ActiveRecord::Base
end

app/models/address_image.rb
class AddressImage < ActiveRecord::Base
end

app/models/address_like.rb
class AddressLike < ActiveRecord::Base
end

app/models/address_post.rb
class AddressPost < ActiveRecord::Base
end

app/models/bch_block.rb
class BchBlock < ActiveRecord::Base
end

app/models/bch_transaction.rb
class BchTransaction < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
  belongs_to :user
end

app/models/follower.rb
class Follower < ActiveRecord::Base
  belongs_to :user, :class_name => 'User', :foreign_key => 'following_id'
  has_one :user, :class_name => 'User', :foreign_key => 'follower_id'

end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  has_attached_file :image, :styles=> { :t => "130x130#", :s => "<400"},
                    :storage => :s3,
                    :s3_credentials => "#{Rails.root}/config/aws.yml",
                    :s3_protocol => "https",
                    :s3_headers => { :cache_control => 30.days.from_now.httpdate },
                    :bucket => Rails.application.config_for(:s3)['general_bucket']

  validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/pjpeg', 'image/jpg', 'image/png', 'image/gif', 'image/bmp', 'image/webp'], :message => "has to be in a proper format"


  def self.find_for_oauth(uid, provider, token, secret, username)
    result = find_or_create_by(uid: uid, provider: provider)
    result.token = token
    result.secret = secret
    result.user_name = username
    result.save!
    result
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, as: :commentable
  belongs_to :user
  belongs_to :sub

  has_attached_file :image, :styles=> { :t => "120x120#", :s => '200x200#', :m => '300x225#', :l => '600x450#'},
                    :storage => :s3,
                    :s3_credentials => "#{Rails.root}/config/aws.yml",
                    :s3_protocol => 'https',
                    :s3_headers => { :cache_control => 30.days.from_now.httpdate },
                    :bucket => Rails.application.config_for(:s3)['general_bucket']
  validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/pjpeg', 'image/jpg', 'image/png', 'image/gif', 'image/bmp'], :message => "has to be in a proper format"

end

app/models/post_image.rb
class PostImage < ActiveRecord::Base
  belongs_to :post

  has_attached_file :image, :styles=> { :s => "<400", :m => "<1024", :l => "<1200"},
                    :storage => :s3,
                    :s3_credentials => "#{Rails.root}/config/aws.yml",
                    :s3_protocol => 'https',
                    :s3_headers => { :cache_control => 30.days.from_now.httpdate },
                    :bucket => Rails.application.config_for(:s3)['general_bucket']
  validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/pjpeg', 'image/jpg', 'image/png', 'image/gif', 'image/bmp'], :message => "has to be in a proper format"

end

app/models/receive_addr.rb
class ReceiveAddr < ActiveRecord::Base
  belongs_to :account
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  has_many :posts
end

app/models/sync_stat.rb
class SyncStat < ActiveRecord::Base
end

app/models/unspent_utxo.rb
class UnspentUtxo < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :account, :through => :account_manager
  has_many :account_manager
  has_many :identity
  devise :database_authenticatable,
         :rememberable,
         :trackable,
         :validatable,
         :registerable,
         :authentication_keys => [:username]

  validates :username, presence: :true, uniqueness: { case_sensitive: false }
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  protected


  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/helpers/user_helper.rb
module UserHelper
  def setup_user(user)
    user.account ||= Account.new
    user
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/layouts/registrations.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <%= render 'layouts/util/og_meta' %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/third_party_trackers/head_codes' %>
  <%= render 'layouts/util/favicons' %>
</head>
<body>
<main role="main">
  <br/><br/>
  <%= render 'layouts/util/messages' %>
  <%= yield %>
</main>

<%= include_gon %>
<%= javascript_include_tag 'application' %>
<%= render 'layouts/third_party_trackers/body_codes' %>
</body>
</html>

app/views/layouts/third_party_trackers/_body_codes.html.erb
<% if !Rails.env.development? %>


<% else %>

    <script type="text/javascript"> 

    var mixpanel = {
                    track: function(){}
                    };
    </script> 

<% end %>

app/views/layouts/third_party_trackers/_head_codes.html.erb
<% if !Rails.env.development? %>


<% end %>

app/views/layouts/util/_favicons.html.erb
<%= favicon_link_tag 'favicon.ico' %>
<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/android-chrome-192x192.png" sizes="192x192">
<link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#00aba9">
<meta name="msapplication-TileImage" content="/mstile-144x144.png">
<meta name="theme-color" content="#ffffff">
 

app/views/layouts/util/_og_meta.erb
<title><%= content_for?(:title) ? yield(:title) : 'BlockPress - Share your content and build your community. Earn Bitcoin Cash.' %></title>
<meta name="description" content="<%= content_for?(:description) ? yield(:description) : 'BlockPress - Share your content and build your community. Earn Bitcoin Cash.' %>">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

<!-- Twitter Card data -->
<meta name="twitter:card" content="BlockPress - Share your content and build your community. Earn Bitcoin Cash.">
<meta name="twitter:site" content="@TheBlockPress">
<meta name="twitter:title" content="<%= content_for?(:title) ? yield(:title) : 'BlockPress - Share your content and build your community. Earn Bitcoin Cash.'  %>">
<meta name="twitter:description" content="<%= content_for?(:description) ? yield(:description) : 'BlockPress - Share your content and build your community. Earn Bitcoin Cash.' %>">
<meta name="twitter:creator" content="@TheBlockPress">
<!-- Twitter Summary card images must be at least 200x200px -->
<meta name="twitter:image" content="<%= content_for?(:image_url) ? yield(:image_url) : get_base_url + '/apple-touch-icon-180x180.png' %>">
<!-- Open Graph data -->
<meta property="og:title" content="<%= content_for?(:og_title) ? yield(:og_title) : 'BlockPress - Share your content and build your community. Earn Bitcoin Cash.' %>"/>
<meta property="og:type" content="<%= content_for?(:og_type) ? yield(:og_type) : 'website' %>"/>

<% if content_for?(:type) && yield(:type) == 'image' %>

    <meta property="og:image" content="<%= content_for?(:image_url) ? yield(:image_url) : get_base_url + '/apple-touch-icon-180x180.png' %>" />
    <!--<meta property="og:image_secure_url" content="<%= content_for?(:image_secure_url) ? yield(:image_secure_url) : get_base_url + '/apple-touch-icon-180x180.png' %>" />-->

	<% if !content_for?(:image_mime_type).blank? %>
		<meta property="og:image:type" content="<%= content_for?(:image_mime_type) ? yield(:image_mime_type) : '' %>" />
	<% end %>

	<meta property="og:image:width" content="<%= content_for?(:image_width) ? yield(:image_width) : '' %>" />
	<meta property="og:image:height" content="<%= content_for?(:image_height) ? yield(:image_height) : '' %>" />

	<meta property="og:url" content="<%= content_for?(:url) ? yield(:url) : 'http://www.blockpress.com' %>"/>

<% else %>
	<meta property="og:image" content="<%= content_for?(:image) ? yield(:image) : get_base_url + '/apple-touch-icon-180x180.png' %>"/>

	<meta property="og:url" content="<%= content_for?(:url) ? yield(:url) : 'http://www.blockpress.com' %>"/>

<% end %>


<meta property="og:description" content="<%= content_for?(:description) ? yield(:description) : 'BlockPress - Share your content and build your community. Earn Bitcoin Cash.' %>"/>
<meta property="og:site_name" content="BlockPress"/>
<meta property="fb:admins" content="1"/>

app/views/layouts/util/_signup_form.html.slim
div.card
  div.card-body
    div.card-title
      h5 style="font-weight: bold;margin-bottom: 1em" Join BlockPress today.

      p.text-muted
        strong
          | Please note:
        =>
        | Your username is only for login purposes and is not visible by anyone else.
        =>
        | Setting your name requires an on-chain BCH transaction to be publicly visible.
    = form_for(:user, url: registration_path(:user), :html => {'role' => 'form'}) do |f|
      = devise_error_messages!
      div.form-group
        = f.text_field :username, tabindex: 1, :class=>'form-control', :placeholder => 'Choose a username', :required => true

      div.form-group
        = f.password_field :password, autocomplete: 'off', tabindex: 2, :class=>'form-control', :placeholder => 'Set a password', :required => true


      div.form-check
        input.form-check-input.key_checkbox type="radio" name="key_check" id="key_check_new" value="key_check_new" checked="checked"
        label.form-check-label for="key_check_new"
          strong
            | Create New WIF/Private Key (Key import coming in future)
          =>
          br
          br
          span.hide style="display: none"
            | (Choose this if you are unsure)

      div.form-check.hide style="display: none"
        input.form-check-input.key_checkbox type="radio" name="key_check" id="key_check_import" value="key_check_import"
        label.form-check-label for="key_check_import"
          strong
            | Import existing key (Uncompressed WIF key)
        br
        br
      div.form-group.d-none id="private_key_input"
        = f.text_field :wif, :class=>'form-control', :placeholder => 'Private key (WIF)'
      = f.submit "Sign up", tabindex: 3, :class => "btn btn-block btn-primary"
    br
    p style="text-align: center; display: none"
      small.text-muted
        | By creating an account, you agree to the
        =>
        a href="/terms"
          | User Agreement.
    p style="text-align: center"
      small.text-muted
        | Already have an account?
        =>
        = link_to "Sign in", new_session_path(:user)